name: CI

on: 
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:unit

